name: pokedex_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  graphql_flutter: ^5.1.2
  flutter_svg: ^1.1.0
  shared_preferences: ^2.3.3
  graphview: ^1.2.0
  flutter_debouncer: ^2.0.0
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/